### ISSUE TITLE
Allow Strings on the x axis

### ISSUE THREAD

**Issue by Brueggus** [tiby312/poloto#101]
Would it be possible to allow String input values on the x-axis, i. e.:

```
    let data = [
        ("Jan 2020", 3144),
        ("Feb 2020", 3518),
        ("Mar 2020", 3835),
    ];
```

**Comment by tiby312** [comment]
@Brueggus I just put a new version out that kind of lets you do this. See the month.rs example.

**Comment by tiby312** [comment]
With the UnixTime plot number type and also with the custom `steps()` function I think this is done basically.
