### ISSUE TITLE
[question] Custom format of tick values

### ISSUE THREAD

**Issue by eknoes** [tiby312/poloto#134]
Thanks for the nice and easy to use crate! I could not really find that out, but is it (already) possible to format the tick values? E.g., I have a graph that has the time that it already ran as number of seconds as x-axis and want to provide some function to a Formatter, that formats it as `Xh Ymin Zsec`.

**Comment by tiby312** [comment]
I just added an example of what I think you are wanting check it out:

[source](https://github.com/tiby312/poloto/blob/master/examples/seconds.rs)
[rendered](https://github.com/tiby312/poloto/blob/master/target/assets/seconds.svg)

works by leveraging chrono's [date time format function]
(https://docs.rs/chrono/latest/chrono/struct.DateTime.html#method.format).

**Comment by eknoes** [comment]
Yes, I did not know ` with_tick_fmt`. Great, thanks for the fast response!
