### ISSUE TITLE
Name of data is truncated

### ISSUE THREAD

**Issue by Icelk** [tiby312/poloto#140]
When adding data, long names are truncated in the SVG. This is due to the dimensions, I believe.

I'd be very grateful if the text would wrap or if it just wouldn't clip.

Great project!

**Comment by tiby312** [comment]
@Icelk good idea. I like the idea of just making the svg image itself wider to fit the text. That sounds like a quick thing to add. Maybe have a `fit_label()` function as well as a `extend_right(usize)`  Would like to eventually be able to do mult-line labels as well but last i checked its not completely straightford as to how to do that with SVG.

**Comment by tiby312** [comment]
@Icelk actually you can already do this after all. I added an example.

[source](https://github.com/tiby312/poloto/blob/master/examples/long_label.rs)

[rendered](https://github.com/tiby312/poloto/blob/master/target/assets/long_label.svg)

**Comment by Icelk** [comment]
Thanks a lot! I’ll be testing this later today.
