### ISSUE TITLE
Option to add empty name / remove bar of colour above

### ISSUE THREAD

**Issue by Icelk** [tiby312/poloto#141]
To display additional information next to the name of the data, I've added an empty [scatter](https://docs.rs/poloto/latest/poloto/struct.Data.html#method.scatter). That however still results in a coloured bar above the text.

Is there potential for an option of removing the bar and or a separate method for showing info there?

Great project!

**Comment by tiby312** [comment]
@Icelk you miiight be able to do this already by specifying the color of that plot to be transparent or the same as the background via css. Try modifying these css classes

poloto[n]fill - If the n'th plot requires fill. (e.g. linefill or histogram)
poloto[n]stroke - If the n'th plot requires stroke. (e.g. line or scatter)

See [this example](https://github.com/tiby312/poloto/blob/master/examples/collatz.rs) for custom css

**Comment by Icelk** [comment]
Sounds good. I’m however worried that if I have several datapoints for which I want the colour to wrap around, this ain’t possible.

Would it be possible to just not output that bit of SVG, at least if the data iterator is empty?

**Comment by Icelk** [comment]
Looks like exactly what I needed. Thanks!
