### ISSUE TITLE
Using `plots!` fails.

### ISSUE THREAD

**Issue by Icelk** [tiby312/poloto#162]
It gives this error message:

```
the method `chain` exists for struct `poloto::build::SinglePlot<std::iter::FilterMap<std::iter::Map<std::ops::Range<{integer}>, [closure@src/bin/main.rs:500:30: 500:99]>, [closure@src/bin/main.rs:504:38: 514:26]>, std::string::String>`, but its trait bounds were not satisfied
```

**only if the trait [PlotIteratorExt](https://docs.rs/poloto/latest/poloto/build/trait.PlotIteratorExt.html#method.chain) isn't imported.** This should be done in the macro.

**Comment by tiby312** [comment]
thank you for the awareness fixed

**Comment by Icelk** [comment]
Thanks!
