### ISSUE TITLE
Replace `.twice_iter` with `Iterator + Clone`?

### ISSUE THREAD

**Issue by matklad** [tiby312/poloto#38]
Hey, I am learning poloto API, and the Double iterator concept feels like it's not necessary?

Feels like the following might be enough?

```rust
    pub fn line_fill<N, I>(&mut self, name: N, plots: I) -> &mut Self
    where
        N: Display + 'a,
        I: IntoIterator<Item = [f64; 2]>,
        I::IntoIter: Clone,
```

**Comment by tiby312** [comment]
@matklad thanks for the feedback! The "problem" that I was thinking about with that is that if you have an expensive iterator, you would have to manually store the results into a vector and pass that into poloto. And I guess the benefit of the current api is the user doesn't have to do that?

**Comment by tiby312** [comment]
I guess I'm saying I think you lose the ability to plot in a "one liner" if you have to store the results in a vector first.

**Comment by tiby312** [comment]
Actually nevermore it's totally possible to do it is one line.

plotter.plot([0;5].iter().map(|x|x+1).collect::<Vec<_>>().iter());

**Comment by tiby312** [comment]
I think the problem with the above code, is that I wanted to make the user have to explicitly say "This iterator will be run through twice", since could be easily overlooked. For example, the gnuplot API doesnt run the iterator twice, so people might assume the same is true for this api, but it is not.

**Comment by tiby312** [comment]
I did some more thinking. There's really 3 options here right. 

1. Make running the iterator twice the default
2. Making buffer the iterator the default
3. Force the user to choose every time. 

Right now the user has to choose every time. The problem with this is that its more verbose. The "pro" is that there is no confusion.  

But now I'm thinking defaulting to twice iterating is better in light of the fact that the user can just user a function like below
to change it to a buffer. 

```

fn buffer<I:IntoIterator>(a:I)->Vec<I::Item>{
    a.into_iter().collect()
}
```

**Comment by tiby312** [comment]
implemented!
